[package]
name = "rust-threads-vs-async"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.19.2", features = ["full"], optional = true }
futures = { version = "0.3.21", optional = true }
hyper = { version = "0.14.19", features = ["http1", "client", "tcp"], optional = true }
ureq = "2.4.0"

[features]
threads = []
async = ["dep:tokio", "dep:futures", "dep:hyper"]

[[bin]]
name = "bin"
path = "main.rs"