[package]
name = "demo-crate-6155"
version = "0.0.0"
description = "Testing crate 2"
license = "MIT"
homepage = "https://crates.io/crates/demo-crate-6154"
edition = "2018"
rust-version = "1.59"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "lib.rs"

[dependencies]
