[package]
name = "codespan-reporting-benchmark"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codespan-reporting = "0.11.1"
source-map = { version = "0.14.10", features = ["codespan-reporting"] }
thousands = "0.2.0"

[patch.crates-io]
codespan-reporting = { git = "https://github.com/kaleidawave/codespan", branch = "static-dispatch-writecolor" }
source-map = { git = "https://github.com/kaleidawave/source-map.git", branch = "codespan-use-str" }

[[bin]]
name = "codespan-reporting-benchmark"
path = "main.rs"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"
debug = false
panic = "abort"
