on:
  workflow_call:
    inputs:
      benchmarks:
        description: "paths to benchmarks, comma seperated"
        type: string
        required: true

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    if: ${{ github.event.inputs.benchmarks == '' }}
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJSON(inputs.benchmarks) }}
  
    env:
      cache: true
      ARTIFACTS_FOLDER: artifacts

    defaults:
      run:
        shell: bash
        working-directory: benchmarks/${{ matrix.path }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/cache@v4
        if: env.cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/home/linuxbrew/
            /cached_targets/
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}

      - run: mkdir -p ${{ env.ARTIFACTS_FOLDER }}
      - name: Make executable
        run: |
          # run.sh might not be executable
          chmod +x run.sh
          chmod +x setup.sh

      - name: Run setup
        run: ./setup.sh

      - name: Run benchmark
        run: ./run.sh

      - id: artifacts_generated
        run: |
          if [ "$(ls -A "${{ env.ARTIFACTS_FOLDER }}")" ]; then
            notEmpty="true"
          else
            notEmpty="false"
          fi
          echo "artifacts_generated=$notEmpty" >> $GITHUB_OUTPUT
          echo "artifacts_generated=$notEmpty" >> $GITHUB_STEP_SUMMARY
  
      - name: Upload artifacts
        if: ${{ steps.artifacts_generated.outputs.artifacts_generated }}
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.path }}
          path: ${{ env.ARTIFACTS_FOLDER }}
