name: Request benchmark

on:
  workflow_dispatch:
    inputs:
      benchmarks:
        description: "paths"
        required: true

jobs:
  run-benchmarks:
    uses: ./.github/workflows/benchmark.yml
    with:
      benchmarks: ${{ format('[{0}]', github.event.inputs.benchmarks) }}
