name: Benchmark things in benchmark folder

on:
  push:
    paths:
      - "benchmarks/**"
      - ".github/workflows/benchmarks.yml"

jobs:
  find-changed-paths:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.read-change.outputs.paths }}
    steps:
      - uses: actions/checkout@v3
        with:
          # Needs two versions to tell difference in change
          fetch-depth: 2
      - name: Read changes
        id: read-change
        shell: bash
        run: |
          # "--no-renames --diff-filter=MCD" ensures only new or modified files. Its a bit weird
          changed_file_paths="$(git diff --no-renames --diff-filter=MCD --name-only HEAD HEAD~1)"
          readarray -t changed_file_paths_array <<< "$changed_file_paths"

          declare -A aa
          for element in "${changed_file_paths_array[@]}"
          do
            # "|| true" to prevent exiting if can't find match then don't exit code 1
            path=$(echo $element | grep -oP "(?<=benchmarks\/)[^\/]*" || true)
            if [ -n "$path" ]; then
              # enclose in quotes here
              aa["'$path'"]=1
            fi
          done

          # thanks https://stackoverflow.com/a/17841619/10048799
          function join_by {
            local d=${1-} f=${2-}
            if shift 2; then
              printf %s "$f" "${@/#/$d}"
            fi
          }

          items=$(join_by , ${!aa[@]})
          echo "::set-output name=paths::[$items]"

  run-benchmarks:
    needs: find-changed-paths
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ !contains(needs.find-changed-paths.outputs.paths, '[]') }}
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJSON(needs.find-changed-paths.outputs.paths) }}
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p artifacts
        working-directory: ${{ format('benchmarks/{0}', matrix.path) }}
      - name: Run benchmark
        run: ./run.sh
        working-directory: ${{ format('benchmarks/{0}', matrix.path) }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ${{ format('benchmarks/{0}', matrix.path) }}/artifacts/
