on:
  workflow_call:
    inputs:
      benchmarks:
        description: "paths to benchmarks, comma seperated"
        type: string
        required: true

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest

    if: ${{ github.event.inputs.benchmarks == '' }}
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJSON(inputs.benchmarks) }}
  
    env:
      cache: true
      ARTIFACTS_FOLDER: artifacts

    defaults:
      run:
        shell: bash
        working-directory: benchmarks/${{ matrix.path }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Get Date
        id: get-date
        run: echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/cache@v4
        if: env.cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/home/linuxbrew/
            **/target/*
          key: ${{ runner.os }}

      - run: mkdir -p ${{ env.ARTIFACTS_FOLDER }}
      
      - name: Make executable
        run: |
          # run.sh and setup.sh might not be executable
          chmod +x run.sh
          chmod +x setup.sh

      - name: Run setup
        run: ./setup.sh
        env:
          GH_TOKEN: ${{ github.token }}
        timeout-minutes: 15

      - name: Run benchmark
        run: ./run.sh
        env:
          ARTIFACTS_FOLDER: ${{ env.ARTIFACTS_FOLDER }}
        timeout-minutes: 5

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: ignore
          name: artifacts-${{ matrix.path }}
          path: ${{ env.ARTIFACTS_FOLDER }}
