name: Dashmap build

on:
  push:
    paths:
      - "dashmap-testing/**"
      - ".github/workflows/dashmap-build.yml"

jobs:
  main:
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     version: ["1.58", "1.59", "1.60", "1.61", "1.62.1"]
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust 1.59
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.59
          override: true
      - run: cargo run
        working-directory: dashmap-testing

      - name: Install Rust 1.60
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.60.0
          override: true
      - run: cargo run
        working-directory: dashmap-testing

      - name: Install Rust 1.61
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.61
          override: true
      - run: cargo run
        working-directory: dashmap-testing
      
      - name: Install Rust 1.62
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.62
          override: true
      - run: cargo run
        working-directory: dashmap-testing