name: Performance (ezno)

on:
  push

jobs:
  flamegraph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'kaleidawave/ezno'
          path: ezno
      - uses: brndnmtthws/rust-action-cargo-binstall@v1
        with:
          packages: flamegraph hyperfine

      - name: Build Ezno
        run: cargo build --release
        working-directory: ezno

      - name: Run flamegraph
        run: |
          echo "# Output" >> $GITHUB_STEP_SUMMARY
          ./target/release/ezno info >> $GITHUB_STEP_SUMMARY

          flamegraph -o my_flamegraph.svg -- /target/release/ezno build ../one-off/ezno/index.js

          echo "### Flamegraph output" >> $GITHUB_STEP_SUMMARY
          cat my_flamegraph.svg >> $GITHUB_STEP_SUMMARY
        working-directory: ezno

      - name: Run hyperfine
        run: |
          hyperfine '/target/release/ezno build ../one-off/ezno/index.js'
          hyperfine '/target/release/ezno build ../one-off/ezno/index.js' >> $GITHUB_STEP_SUMMARY
        working-directory: ezno
      