name: Deploy shuttle project

on:
  push:
    paths:
      - "one-off/shuttle-secrets-test/**"
      - ".github/workflows/deploy-shuttle-secrets.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo 'TOKEN2="le token deux"' >> Secrets.toml
        working-directory: one-off/shuttle-secrets-test
      - uses: kaleidawave/shuttle-deploy-action@patch-1
        with:
          deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
          working-directory: one-off/shuttle-secrets-test