name: Deploy shuttle project

on:
  push:
    paths:
      - "one-off/server/**"
      - ".github/workflows/deploy-mongodb-server.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
          working-directory: one-off/server
          allow-dirty: true