name: Deploy mongodb server project

on:
  push:
    paths:
      - "one-off/mongo-db-server/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
          working-directory: one-off/deploy-mongodb-server/server