name: Testing things

on:
  push:
    branches:
      - "*"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hi
      # - name: Add secrets
      #   run: |
      #     echo 'DISCORD_TOKEN="${{ secrets.DISCORD_KEY }}"' >> Secrets.toml
      #     echo 'WEATHER_API_KEY="${{ secrets.WEATHER_API_KEY }}"' >> Secrets.toml
      #     cat Secrets.toml
      #     cat Secrets.toml >> $GITHUB_STEP_SUMMARY
      - name: Get private repo
        run: |
          gh auth status
          gh repo list kaleidawave
          gh repo clone kaleidawave/aoc20 aoc20
          ls -R aoc20
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_PRIVATE_KEY }}