name: Get video

on:
  push:
    paths:
      - "video/video-requests.txt"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Install & setup
        run: |
          brew install yt-dlp/taps/yt-dlp
          brew install ffmpeg
      - name: Download and trim
        run: |
          line=$(tail -n 1 video-requests.txt)
          items=($line)
          yt-dlp ${items[0]} --output videos/output.mp4
          ffmpeg -i videos/output.mp4 -ss ${items[1]} -to ${items[2]} -c:v copy -c:a copy videos/output.mp4
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: videos
          path: |
            videos