name: Get video

on:
  push:
    paths:
      - "video/video-requests.txt"
      - ".github/workflows/get-video.yml"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install & setup
        run: |
          brew install yt-dlp/taps/yt-dlp
          brew install ffmpeg
      - name: Download and trim
        run: |
          line=$(tail -n 1 video-requests.txt)
          items=($line)
          yt-dlp ${items[0]} -o output.mp4 -f mp4
          echo "Snipping out ${items[1]} to ${items[2]}"
          ffmpeg -i output.mp4 -ss "${items[1]}" -to "${items[2]}" -y cut-output.mp4
          rm output.mp4
          mv cut-output.mp4 output.mp4
        working-directory: video
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: video
          path: |
            video