name: Get video

on:
  push:
    paths:
      - "video/video-requests.txt"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install & setup
        run: |
          brew install yt-dlp/taps/yt-dlp
          brew install ffmpeg
      - name: Download and trim
        run: python script.py
        working-directory: video
        shell: bash
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: video
          path: |
            video
          retention-days: 3