name: Deploy NPM project

on:
  push:
    paths:
      - "one-off/npm-package/**"
      - ".github/workflows/npm-publish.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: NPM publish
        run: |
          npm ci
          npm publish
        working-directory: one-off/npm-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}