name: Testing things

on:
  push:
    paths:
      - ".github/workflows/push.yml"
      - "one-off/**/*"

jobs:
  reply_to_conversation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const query = `mutation($discussionId:ID!, $body:String!) {
              # input type: AddDiscussionCommentInput
              addDiscussionComment(input: {
                discussionId: $discussionId, 
                body: $body
              }) {

                # response type: DiscussionComment
                comment {
                  updatedAt, id, databaseId, bodyText, url,
                  author {
                    ...
                  }
                }
              }
            }`;

            const variables = {
              discussionId: 'D_kwDOHITK2c4AgQ1N',
              body: 'this is a reply',
            }
            const result = await github.graphql(query, variables)

            core.info(`Discussion reply created: ${result.createDiscussion.discussion.url}`);
            core.info(`Discussion reply created: ${JSON.stringify(result)}`);
