name: Testing things

on:
  push:
    paths:
      - ".github/workflows/push.yml"
      - "one-off/**/*"

jobs:
  comparse-ezno-and-typescript:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: kaleidawave/release-downloader@improvements
        env:
          GH_TOKEN: ${{ github.token }}
        with: { 'items': 'sharkdp/hyperfine@v1.19.0' }

      - name: download ezno
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run download -R kaleidawave/ezno --pattern binary-LinuxX64-general-fixes-last
          mv binary-LinuxX64-general-fixes-last/binary-LinuxX64-general-fixes-last ezno
          chmod +x ./ezno
          ./ezno --help

      - name: download tsgo
        continue-on-error: true
        run: |
          npm install @typescript/native-preview-linux-x64
          mv node_modules/@typescript/native-preview-linux-x64/lib/tsgo

      - name: Build latest version of demo.tsx
        run: curl https://gist.githubusercontent.com/kaleidawave/81066f322ed574b3373e27770137013f/raw/b04dcc0bc60e6331008bdd578b98224cc07d5d42/all.tsx > demo.tsx

      - name: ezno
        continue-on-error: true
        run: ./ezno check demo.tsx --timings

      - name: tsc
        continue-on-error: true
        run: ./node_modules/@typescript/native-preview-linux-x64/lib/tsgo --noEmit --jsx preserve --skipLibCheck --diagnostics demo.tsx
        
      - name: run performance test
        continue-on-error: true
        run: hyperfine -N -i './ezno check demo.tsx' './node_modules/@typescript/native-preview-linux-x64/lib/tsgo --noEmit --jsx preserve --skipLibCheck demo.tsx'

  sde-linux:
    if: false

    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    steps:
      - name: Setup SDE binaries
        uses: petarpetrovt/setup-sde@v3.0
        with:
          environmentVariableName: SDE_PATH # default value is `SDE_PATH`
          sdeVersion: 9.58.0 # possible values: 9.58.0 (default), 9.33.0

      - name: fix
        run: echo "$SDE_PATH" >> $GITHUB_PATH

      - name: run1
        continue-on-error: true
        run: sde --help

      - name: Download binaries 1
        uses: kaleidawave/release-downloader@improvements
        with:
          items: kaleidawave/experiments@assets[format-number]

      - name: run2
        continue-on-error: true
        run: |
          sde -mix -mix_filter_no_shared_libs -- format-number 42 --english
          sde -omix out1.txt -mix_filter_no_shared_libs -- format-number 42 --english

      - name: run2.1
        continue-on-error: true
        run: | 
          ls
          cat out1.txt

      - uses: actions/upload-artifact@v4
        with:
          name: out
          path: out1.txt
          retention-days: 7

      - uses: brndnmtthws/rust-action-cargo-binstall@v1
        with:
          packages: ripgrep

      - name: run3
        run: rg --help

      - name: run4
        continue-on-error: true
        run: |
          sde -omix out2.txt -mix_filter_no_shared_libs -- format-number 42 --english
          cat out2.txt | rg -e "\*total" | last

  test-release-downloader-action-reference:
    if: false

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    env:
      GH_TOKEN: ${{ github.token }}
    
    steps:
    - name: Download binaries 1
      uses: kaleidawave/release-downloader@improvements
      with:
        items: kaleidawave/experiments@assets[format-number|parse-number|spectra]

    - name: run output
      run: |
        format-number --help
        parse-number --help
        format-number 42 --english
        parse-number 'fourty two' --english 
        spectra --help
        which 'spectra'

  lines-of-code-on-ezno:
    if: false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: kaleidawave/ezno
    - name: Download binaries 1
      uses: kaleidawave/release-downloader@improvements
      with:
        items: kaleidawave/experiments@assets[lines-of-code]
        trace: true

    - name: lines of code in Ezno
      run: | 
        lines-of-code checker/**/*.rs
        lines-of-code parser/**/*.rs

  test-mkdir-on-windows-bash:
    if: false

    runs-on: windows-latest

    steps:
    - name: run 1
      shell: bash
      continue-on-error: true
      run: |
        mkdir -p "$HOME/test1"
        ls $HOME

    - name: run 2
      shell: bash
      continue-on-error: true
      run: |
        echo "hi" > "$HOME/test2/file1"
        ls $HOME
        ls '$HOME/test2'
        cat '$HOME/test2/file1'

  build-exe-parser:
    if: false
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        repository: N0fix/rpecli
    - uses: dtolnay/rust-toolchain@stable

    - name: Build
      run: cargo build --bin rpecli

    - id: upload
      uses: actions/upload-artifact@v4
      with:
        name: result
        path: target/debug/**/*.exe
        retention-days: 3

  release-download1:
    if: false

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
    - id: run
      run: |
        IFS=',' read -ra entries <<< 'kaleidawave/experiments@assets[spectra],sharkdp/hyperfine@v1.19.0[hyperfine]'
        # IFS=',' read -ra entries <<< '$ { { inputs.items }}'

        BIN="$HOME/.local/bin"
        mkdir -p "$BIN"

        ls -R "$HOME/.local"

        # Loop through each entry
        for entry in "${entries[@]}"; do
          # Extract owner and the rest
          owner="${entry%%/*}"
          rest="${entry#*/}"

          # Extract repository and the rest
          repository="${rest%%@*}"
          rest="${rest#*@}"

          # Extract version and item
          version="${rest%%[*}"
          item="${rest#*[}"
          item="${item%]}"  # remove trailing ]

          echo "$owner/$repository @ $version get item $item"

          gh release download -R "$owner/$repository" $version -p $item -D $BIN
        done

        gunzip "$BIN/**/*.gz"
        tar -xf "$BIN/**/*.tar" -C $BIN --strip-components 1 --overwrite

        for file in "$BIN/**/*"; do
          echo "$file"
          if [ -f "$file" ]; then 
            if head -c 4 "$file" | grep -q $'\x7fELF'; then
              chmod +x "$file"
            fi
          fi
        done

        echo "$BIN" >> "$GITHUB_PATH"
      shell: bash

    # test
    - uses: actions/checkout@v4
      with:
        repository: kaleidawave/experiments
        ref: general-parser
    - uses: dtolnay/rust-toolchain@stable

    - name: Test
      run: cargo test
      working-directory: general-parser

    - name: hypefine
      run: hypefine --help

    - name: git
      run: git diff

  test-version-thingy:
    if: false

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
    - uses: actions/checkout@v4
      with:
        repository: kaleidawave/experiments
        ref: general-parser

    - uses: kaleidawave/release-downloader@main
      with:
        items: kaleidawave/crates-release-gh-action@assets[crates-release]

    - name: Update versions
      id: update-versions
      run: crates-release change-version patch --github-actions-outputs
      working-directory: general-parser

    - run: echo '${{ toJson(steps.update-versions.outputs) }}'
    - run: git diff

