name: Testing things

on: { push: { paths: [".github/workflows/push.yml", "one-off/**/*"] } }

jobs:
  build-depict-assets:
    if: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: windows-latest
          platform-name: x86_64-pc-windows
          executable-extension: ".exe"
        - os: ubuntu-latest
          platform-name: x86_64-unknown-linux
        - os: macos-latest
          platform-name: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    env:
      PROFILE: dev
      OUT: target/debug
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v6
        with: { repository: kaleidawave/depict, path: depict }
      - uses: dtolnay/rust-toolchain@stable

      # build dependents

      - uses: jwlawson/actions-setup-cmake@v2
        if: ${{ matrix.os == 'macos-latest' }}
        with: { cmake-version: '3.31.7' }
      
      - name: Get QBDI (macos)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          curl https://github.com/QBDI/QBDI/releases/download/v0.12.0/QBDI-0.12.0-osx-AARCH64.pkg -L > QBDI.pkg
          sudo installer -pkg QBDI.pkg -target ~
          bash build-qbdi.sh

      # end build dependents

      - name: Build binary
        run: cargo build --profile ${{ env.PROFILE }}

      - name: Add output
        uses: actions/upload-artifact@v4
        with:
          name: depict-${{ matrix.platform-name }}${{ matrix.executable-extension }}
          path: ${{ env.OUT }}/depict${{ matrix.executable-extension }}

      # - name: Publish binary
      #   shell: bash
      #   run: |
      #     FROM='${{ env.OUT }}/depict${{ matrix.executable-extension }}'
      #     TO='depict-${{ matrix.platform-name }}${{ matrix.executable-extension }}'
      #     mv $FROM $TO
      #     gh release upload $GH_RELEASE "$TO" --clobber


  ezno-perf:
    if: false
    runs-on: ubuntu-latest

    # permissions: { contents: write }

    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6
        with: { repository: kaleidawave/depict, path: depict }
      - uses: actions/checkout@v6
        with: { repository: kaleidawave/ezno, ref: parser-fixes, path: ezno }
      - uses: kaleidawave/release-downloader@improvements
        env: { GH_TOKEN: '${{ env.GH_TOKEN }}' }
        with: { items: 'kaleidawave/experiments@assets[shell-language],sharkdp/hyperfine@v1.19.0' }

      - name: Install depict
        working-directory: depict
        run: cargo r -- install-sde

      - name: Build ezno
        working-directory: ezno
        run: cargo b --release

      - name: Run example
        shell: shell-language {0}
        run: |
          let path = literal 'https://gist.githubusercontent.com/kaleidawave/81066f322ed574b3373e27770137013f/raw/b04dcc0bc60e6331008bdd578b98224cc07d5d42/all.tsx'
          run curl $path -o demo.tsx

          run npm install @typescript/native-preview-linux-x64

          let depict_ezno = run ./depict/target/debug/depict count --breakdown ./ezno/target/release/ezno check demo.tsx
          echo $depict_ezno
          
          let ts = run ./node_modules/@typescript/native-preview-linux-x64/lib/tsgo --noEmit --jsx preserve --skipLibCheck --diagnostics demo.tsx
          let statistics = rafter $ts "Files:" then trim
          echo $statistics

          let out = run hyperfine -N -i \
            './node_modules/@typescript/native-preview-linux-x64/lib/tsgo --noEmit --jsx preserve --skipLibCheck --diagnostics demo.tsx' \
            './ezno/target/release/ezno check demo.tsx --timings'
          echo $out

      - name: for those at the back
        if: ${{ always() }}
        run: |
          hyperfine -N -i \
            './node_modules/@typescript/native-preview-linux-x64/lib/tsgo --noEmit --jsx preserve --skipLibCheck demo.tsx' \
            './ezno/target/release/ezno check demo.tsx'
