name: Issue create

on:
  push:
    branches-ignore:
      - "**"

jobs:
  show_error:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context);
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Issue for: ${context.sha}`,
              body: "Hiya 👋"
            });
