name: Crates release thingy

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        run: git remote -v
      - uses: actions/checkout@v3
        with:
          clean: false
      - name: Edit 
        id: checkout
        run: | 
          echo "// Some comment" >> cargo-testing-version/src/main.rs
          cat cargo-testing-version/src/main.rs
          git diff
          git status
          echo "::set-output name=checkout::$( git remote -v )"
      - uses: actions/checkout@v3
        if: ${{ !constains(steps.checkout.outputs.checkout, github.repository) }}
        with:
          clean: false
      - name: check still valid 
        run: |
          cat cargo-testing-version/src/main.rs
          git diff
          git status
      - name: Get latest cargo-edit version
        id: cargo-edit-version
        run:
          echo "::set-output name=CARGO_EDIT_API_RESPONSE::$( 
            curl https://formulae.brew.sh/api/formula/cargo-edit.json
          )"
        shell: bash
      - name: test1
        if: ${{ contains(fromJSON('["major","minor","patch","release","rc","beta","alpha"]'), 'minor') }}
        run: >
          echo a
        shell: bash
      - name: test2
        if: ${{ contains(fromJSON('["major","minor","patch","release","rc","beta","alpha"]'), 23) }}
        run: >
          echo b
        shell: bash
      - name: test3
        run: >
          echo "${{ join(fromJSON('["major","minor","patch","release","rc","beta","alpha"]'), ',') }}"
        shell: bash
      - uses: actions/cache@v3
        id: cache-cargo-edit
        with:
          path: |
            /home/linuxbrew/.linuxbrew/Cellar
            /usr/share/rust/.cargo/bin
          key: |
            cargo-edit-${{ runner.os }}-${{ fromJSON(steps.cargo-edit-version.outputs.CARGO_EDIT_API_RESPONSE).versions.stable }}-3
      - name: Show cache hit
        if: steps.cache-cargo-edit.outputs.cache-hit == 'true'
        run: |
          echo "cache hit! :)"
          cargo --list
      - name: Install cargo edit
        if: steps.cache-cargo-edit.outputs.cache-hit != 'true'
        run: |
          echo "::group::Installing cargo edit"
          brew install cargo-edit
          echo "::endgroup::"
        shell: bash
      - name: Show install
        run: |
          which cargo
          cargo --list
        shell: bash
      - name: Change version
        working-directory: cargo-testing-version
        run: |
          echo "NEW_CRATE_VERSION=$( 
            (cargo set-version --bump minor 2>&1) | awk 'NR==1 {print $NF}'
          )" >> $GITHUB_ENV
        shell: bash
      - name: Check version set
        if: env.NEW_CRATE_VERSION == ''
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Error with the output of the new version')
      - name: Show new version
        run: echo "New version ${{ env.NEW_CRATE_VERSION }}"
        shell: bash