name: GitHub Actions Demo

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
      - name: Get latest cargo-edit version
        id: cargo-edit-version
        run:
          echo "::set-output name=CARGO_EDIT_API_RESPONSE::$( 
            curl https://formulae.brew.sh/api/formula/cargo-edit.json
          )"
        shell: bash
      - uses: actions/cache@v3
        id: cache-cargo-edit
        with:
          path: |
            /home/linuxbrew/.linuxbrew/Cellar
            /usr/share/rust/.cargo/bin
          key: |
            cargo-edit-${{ runner.os }}-${{ fromJSON(steps.cargo-edit-version.outputs.CARGO_EDIT_API_RESPONSE).versions.stable }}2
      - name: Show cache hit
        if: steps.cache-cargo-edit.outputs.cache-hit == 'true'
        run: |
          echo "cache hit! :)"
          cargo set-version -V
      - name: Install cargo edit
        if: steps.cache-cargo-edit.outputs.cache-hit != 'true'
        run: |
          echo "::group::Installing cargo edit"
          brew install cargo-edit
          echo "::endgroup::"
        shell: bash
      - name: Show install
        run: |
          which cargo
          ls /home/linuxbrew/.linuxbrew/bin/cargo
          ls /usr/share/rust/.cargo/bin
        shell: bash
      - name: Change version
        working-directory: cargo-testing-version
        run: |
          echo "$( 
            cargo set-version --bump minor
          )"
          echo "NEW_CRATE_VERSION_VERBOSE=$( 
            cargo set-version --bump minor
          )" >> $GITHUB_ENV
          echo "${{ toJSON(env.NEW_CRATE_VERSION_VERBOSE) }}"
          echo "NEW_CRATE_VERSION=$( 
            cargo set-version --bump minor | awk 'NR==1 {print $NF}' 
          )" >> $GITHUB_ENV
      - name: Check version set
        if: env.NEW_CRATE_VERSION == ''
        run: ">&2 echo 'error no version'"
        shell: bash
      - name: Show new version
        run: echo "New version ${{ env.NEW_CRATE_VERSION }}"
        shell: bash
      - name: bye
        run: echo bye
