name: Do test stuff

on:
  push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hi
      - name: Add secrets
        run: |
          echo 'DISCORD_TOKEN="${{ secrets.DISCORD_KEY }}"' >> Secrets.toml
          echo 'WEATHER_API_KEY="${{ secrets.WEATHER_API_KEY }}"' >> Secrets.toml
          cat Secrets.toml
          cat Secrets.toml >> $GITHUB_STEP_SUMMARY
