name: Rust http benchmark

on:
  push:
    paths:
      - "rust-http-benchmark/**"
      - ".github/workflows/test-benchmark.yml"

jobs:
  find-paths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # todo temp 
          fetch-depth: 5
      - run: git status
      - name: Read changes
        run: |
          # todo HEAD~1
          changed_file_paths="$(git diff --name-only HEAD HEAD~5)"
          readarray -t changed_file_paths_array <<< "$changed_file_paths"
          declare -A aa
          for element in "${changed_file_paths_array[@]}"
          do
              # also enclose in quotes
              path="'$(echo $element | grep -oP "(?<=rust-http-benchmark\/)[^\/]*")'"
              aa[$path]=1
          done

          function join_by {
            local d=${1-} f=${2-}
            if shift 2; then
              printf %s "$f" "${@/#/$d}"
            fi
          }

          items=$(join_by , ${!aa[@]})
          echo "::set-output name=paths::[$items]"

  run-benchmarks:
    needs: find-paths
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix: 
        path: ${{fromJSON(needs.find-paths.outputs.paths)}}
    steps:
      - run: brew install wrk
      - name: build
        run: |
          # TODO timings
          cargo build
        working-directory: format('rust-http-benchmark/{0}', matrix.path)
      - name: benchmark
        run: |
          ./target/debug/${{ matrix.path }} &
          wrk -t12 -c200 -d30s http://127.0.0.1:3000
        working-directory: format('rust-http-benchmark/{0}', matrix.path)

      